### ISSUE TITLE
app.weploy.ai FIXES!

### ISSUE THREAD

**Issue by 2567910** [desentio/weploy-translate#17]
- [x] Banner that explains on project creation that it will translate once you load the website, and it will take some time. (only comes when project/edit/0) - When you create a project on weploy /edit/0 it should show a banner that explains the translations are created on the first time you visit your website. This means initial the load time of the translations will be very slow since the AI has to create them first.
- [x] Link integration guides from Webflow do not show markdown like before. 
- [x] Show integration codes! (They were in markdown before)
- [x] Change color of the logo so it's same as in webflow. 
- [x] Show language switcher options (Darkmode and non dakrmode)

**Comment by jemikanegara** [comment]
- [ ] change the prime color

**Comment by jemikanegara** [comment]
- [ ] use-browser-language
