### ISSUE TITLE
New language switch requirements

### ISSUE THREAD

**Issue by 2567910** [desentio/weploy-translate#21]
The select is what forms the first impression from our customers as well as the customers users. If it looks amazing, than the customer might overlook the SEO thing. 

- [x] The language switcher is always there even if our api is down. 
- [x] the script should work without calling getProjectByKey (Only call if the script is missing something)
- [x] The language switcher should be loaded instantly in the loading state. (Later if we know what language the user has we switch language. Before that it is just loading. 
- [x] click outside of dropdown to close it
- [x] Loading animation different (@2567910 )
- [x] once i click a language the popup needs to close and it should start loading

TODO later:
-maybe we shouw an error symbol if the request fails.

**Comment by jemikanegara** [comment]
- [ ] set width

**Comment by jemikanegara** [comment]
update icons:
- hide lang when loading & initial
- make it smaller (20px)
- display flex + margin left on the lang
