### ISSUE TITLE
WEPLOY fix

### ISSUE THREAD

**Issue by 2567910** [desentio/weploy-translate#3]
We need to make sure that users cannot translate something from german to german. This is currently happening if you trigger a useffect but the text is already translated. (This could happen in production?)

There is a simple fix fot that. 

If the backend gets translation request like {toLanguaguage="DE", defaultLanguage="EN" } just check the **find string with more then one word** in the strings array and check if the original value is already a translation result in the database. 

Example:

Input: {toLanguaguage="DE", defaultLanguage="EN", string: "Das ist Deutsch" }
Backend: check in db if translation from en to DE with translation result  "Das ist Deutsch" already exists. If so this is an invalid request because the input string is not english.

Output: {400 Error The input language does not match the expacted default lang input.}

{"weploy" (EN) -> translations "weploy" DE }

**Comment by 2567910** [comment]
![Image](https://github.com/desentio/weploy-translate/assets/22271360/6b2d166b-c14d-478f-ae1c-6915caaa17b2)

**Comment by jemikanegara** [comment]
- [ ] filter out spacing (backend)
- [ ] move filter to new tab (app)
- [ ] send the language label to AI (backend)

**Comment by jemikanegara** [comment]
![Image](https://github.com/desentio/weploy-translate/assets/42384614/4ff8d25c-2f07-407a-a1da-b747fc2656f5)
